artifact_location: file:///D:/personal/study_Sem1/Thesis/Learning/OFA/OFA_YOLO/runs/mlflow/425886584850374518
creation_time: 1741786010356
experiment_id: '425886584850374518'
last_update_time: 1741786010356
lifecycle_stage: active
name: runs\yolov8_ofa_project
