artifact_location: file:///D:/personal/study_Sem1/Thesis/Learning/OFA/OFA_YOLO/runs/mlflow/0
creation_time: 1741786010356
experiment_id: '0'
last_update_time: 1741786010356
lifecycle_stage: active
name: Default
